spring.application.name=ai-library-team3-batch

# ===============================
# Datasource (DBCP2)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/team3-library?stringtype=unspecified
spring.datasource.username=team3
spring.datasource.password=5IQCFmyhKvVu8Zvx

spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=1000
